language: elixir
sudo: false

elixir:
  - 1.2.4

addons:
  postgresql: "9.4"

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install v5.10.0
  - nvm use v5.10.0
  - npm install -g gulp bower

before_script:
  - mix local.hex --force
  - mix deps.get
  - npm install --prefix ./frontend
  - bower install --config.cwd=./frontend
  - psql -c 'create database travis_ci_test;' -U postgres
  - export DATABASE_URL='postgres://postgres@localhost:5432/travis_ci_test'
